[package]
name = "rouillespy"
version = "0.1.0"
edition = "2021"

# Add your dependencies here
[dependencies]
log = "0.4"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"



# Optional: specify binary target
[[bin]]
name = "rouillespy"
path = "src/rouillespy.rs"
