// cookies.rs
//use std::collections::HashMap;
use tokio::fs;

/*
   These cookies use a printf-style type indicator, see 'man 3 printf'.
   Types to be used are: %d = decimal, %f = float and %s = string.
   WARNING: Be sure the above types are used correctly with the right cookie.
   Example: FREESPACE     %[%.1f]FMB = 755.5MB
	    EMAIL         %[%-13.13s]E = root@127.0.0.
	    COUNTER       %[%02d]c = 01
	    TRANSFER RATE %[%.2f]AK/s = 150.23K/s
*/

/// Cookie definitions
pub const COOKIE_DEFINITIONS: &[(&str, &str)] = &[
    // General Cookies
    ("%[%f]A", "Last realtime average transfer rate in KiB/s"),
    ("%[%f]F", "Free space in CWD in MiB"),
    ("%[%f]X", "Free space in CWD in size set by the display_size_unit setting"),
    ("%[%s]E", "Email address, empty if no email setting exists"),
    ("%[%d]M", "Max # of users allowed online"),
    ("%[%s]T", "Current time and date"),
    ("%[%s]D", "Date and time current file was last modified, n/a if no file"),
    ("%[%s]R", "Remote host"),
    ("%[%s]H", "Hostname"),
    ("%[%s]S", "Sitename long format, SITE if no sitename_long setting exists"),
    ("%[%s]s", "Sitename short format, SITE if no sitename_short setting exists"),
    ("%[%d]c", "Counter"),
    ("%[%s]d", "Current working directory, dirname only"),
    ("%[%s]b", "Name of current section (based on pwd)"),
    ("%[%s]a", "Name of requested section (based on user input or related stats)"),
    ("%[%s]P", "Type of TLS connection: ctrl&data|ctrl|none"),
    ("%[%d]B*", "# of users currently logged in (can use any symbol instead of *)"),
    ("%[%d]Bo", "# of users currently logged in excluding the hidden users"),
    ("%[%s]V", "Speed unit to display"),
    ("%[%s]Y", "Size unit to display"),
    // User Cookies
    ("%[%s]Iu", "Username"),
    ("%[%s]I$", "User's comment"),
    ("%[%s]I!", "User's expiring date as YYYY-MM-DD or Never if 0"),
    ("%[%s]I-", "The user that added this user"),
    ("%[%s]Iy", "Groups: long string separated by spaces"),
    ("%[%s]IY", "Private groups: long string separated by spaces"),
    ("%[%s]IZ", "User's flags"),
    ("%[%s]Ir", "Ratio for UpLoad and DownLoad"),
    ("%[%s]Id", "Has messages waiting: Y|N"),
    ("%[%s]IE", "Shows the timeframe: XX:00-YY:00"),
    ("%[%d]If", "Total # of files uploaded"),
    ("%[%d]IF", "# of files uploaded this call"),
    ("%[%d]Ig", "# of files uploaded this week"),
    ("%[%d]Ia", "# of files uploaded this month"),
    ("%[%d]IA", "# of files uploaded this day"),
    ("%[%f]IG", "Total # of bytes uploaded in size set by the display_size_unit setting"),
    ("%[%f]IH", "# of bytes uploaded this call in size set by the display_size_unit setting"),
    ("%[%f]Ih", "# of bytes uploaded this week in size set by the display_size_unit setting"),
    ("%[%f]Ib", "# of bytes uploaded this month in size set by the display_size_unit setting"),
    ("%[%f]IB", "# of bytes uploaded this day in size set by the display_size_unit setting"),
    ("%[%d]Ii", "Total # of files downloaded"),
    ("%[%d]Ij", "# of files downloaded this call"),
    ("%[%d]II", "# of files downloaded this week"),
    ("%[%d]In", "# of files downloaded this month"),
    ("%[%d]IN", "# of files downloaded this day"),
    ("%[%f]IJ", "Total # of bytes downloaded in size set by the display_size_unit setting"),
    ("%[%f]Ik", "# of bytes downloaded this week in size set by the display_size_unit setting"),
    ("%[%f]IK", "# of bytes downloaded this call in size set by the display_size_unit setting"),
    ("%[%f]Ip", "# of bytes downloaded this month in size set by the display_size_unit setting"),
    ("%[%f]IP", "# of bytes downloaded this day in size set by the display_size_unit setting"),
    ("%[%f]ID", "Average download rate in speed set by the display_speed_unit setting"),
    ("%[%f]IS", "Average download rate this day in speed set by the display_speed_unit setting"),
    ("%[%f]IV", "Average download rate this week in speed set by the display_speed_unit setting"),
    ("%[%f]Iv", "Average download rate this month in speed set by the display_speed_unit setting"),
    ("%[%f]IU", "Average upload rate in speed set by the display_speed_unit setting"),
    ("%[%f]Is", "Average upload rate this day in speed set by the display_speed_unit setting"),
    ("%[%f]Iq", "Average upload rate this week in speed set by the display_speed_unit setting"),
    ("%[%f]IQ", "Average upload rate this month in speed set by the display_speed_unit setting"),
    ("%[%f]IR", "Overall average transfer rate in speed set by the display_speed_unit setting"),
    ("%[%s]It", "User's tagline"),
    ("%[%s]IT", "How long ago user was online, in days, hours and minutes"),
    ("%[%d]Iw", "Time limit in minutes"),
    ("%[%f]Ic", "Amount of credits in size set by the display_size_unit setting"),
    ("%[%d]IL", "Total number of times user has logged in"),
    ("%[%s]IM", "Max # of simultaneous logins for user or Unlimited if 0"),
    ("%[%s]I#", "Max # of simultaneous logins from the same IP or Unlimited if 0"),
    ("%[%d]Im", "Number of times user is currently logged in"),
    ("%[%s]Io", "Time online this call"),
    ("%[%s]Ie", "Time online today"),
    ("%[%s]IC", "When user was added to system"),
    ("%[%f]IW", "Weekly allotment in size set by the display_size_unit setting"),
    ("%[%s]Il", "How long ago last nuked, in days, hours and minutes"),
    ("%[%d]IO", "Times nuked"),
    ("%[%f]Ix", "Bytes nuked in size set by the display_size_unit setting"),
    ("%[%s]I0", "User's IP #0"),
    ("%[%s]I1", "User's IP #1"),
    ("%[%s]I2", "User's IP #2"),
    ("%[%s]I3", "User's IP #3"),
    ("%[%s]I4", "User's IP #4"),
    ("%[%s]I5", "User's IP #5"),
    ("%[%s]I6", "User's IP #6"),
    ("%[%s]I7", "User's IP #7"),
    ("%[%s]I8", "User's IP #8"),
    ("%[%s]I9", "User's IP #9"),
    ("%[%f]Iz", "User's max allowed download speed in size set by the display_speed_unit setting"),
    ("%[%f]I&", "User's max allowed upload speed in size set by the display_speed_unit setting"),
    ("%[%s]I^", "User's max simultaneous uploads or Unlimited if -1"),
    ("%[%s]I*", "User's max simultaneous downloads or Unlimited if -1"),
    ("%[%s]I+", "Last time and date we saw the user"),
    ("%[%s]I@", "Maximum individual idle time or Disabled if -1"),
    ("%[%s]IX", "List of credits ordered by stat_section"),
    ("%[%s]I=", "List of ratios ordered by stat_section"),
    // Flags Cookies
    ("%[%s]fX", "User flag status"),
    // Group Cookies
    ("%[%s]Cg", "Group name"),
    ("%[%s]Cc", "Group comment"),
    ("%[%s]CS", "# of free slots"),
    ("%[%s]Cl", "# of free leech slots"),
    ("%[%s]Ca", "# of free weekly allotment slots"),
    ("%[%s]Cw", "Maximum weekly allotment size per user"),
    ("%[%s]Cs", "Maximum number of simultaneous logged in users"),
    ("%[%s]Ci", "Group info"),
    // Ginfo Cookies
    ("%[%s]ga", "User's ratio"),
    ("%[%f]gb", "User's bytes up"),
    ("%[%f]gc", "User's bytes down"),
    ("%[%d]gf", "User's files up"),
    ("%[%d]gg", "User's files down"),
    ("%[%s]gu", "Username prepended with special characters"),
    ("%[%s]gt", "Tagline"),
    ("%[%f]gW", "Weekly allotment size"),
    ("%[%d]gk", "Number of users"),
    ("%[%d]gl", "Number of leechers"),
    ("%[%d]gx", "Total files up"),
    ("%[%d]gy", "Total files down"),
    ("%[%f]gm", "Total bytes up"),
    ("%[%f]gn", "Total bytes down"),
    ("%[%s]gh", "# of free slots"),
    ("%[%s]gi", "# of free leech slots"),
    ("%[%s]gj", "# of free weekly allotment slots"),
    // Show Totals Cookies
    ("%[%s]Zu", "Uploader"),
    ("%[%s]Zg", "Group"),
    ("%[%s]Zb", "Total bytes by uploader"),
    ("%[%s]Zf", "Total files by uploader"),
    ("%[%f]Zp", "Percentage of total bytes sent by uploader"),
    ("%[%f]ZP", "Total percentage"),
    ("%[%s]ZB", "Total bytes in directory"),
    ("%[%s]ZF", "Total files in directory"),
    // Who's Online Cookies
    ("%[%s]Wa", "User's action"),
    ("%[%s]Wo", "User's time online"),
    ("%[%s]Wi", "User's idle time"),
    ("%[%s]WI", "Time since last successful transfer"),
    ("%[%s]Wu", "Username"),
    ("%[%s]Wg", "User's primary group"),
    ("%[%s]Wp", "User's PID"),
    ("%[%s]Wd", "User's current working directory"),
    ("%[%s]Wh", "User's remote hostname"),
    ("%[%s]Wt", "User's tagline"),
    ("%[%s]Ws", "Type of TLS connection"),
    ("%[%s]Wx", "Total upload speed by all visible users"),
    ("%[%s]Wy", "Total download speed by all visible users"),
    // Oneliners Cookies
    ("%[%s]ou", "User who added the oneliner"),
    ("%[%s]og", "User's primary group"),
    ("%[%s]ot", "User's tagline"),
    ("%[%s]oD", "Day oneliner was added"),
    ("%[%s]oM", "Month oneliner was added"),
    ("%[%s]oY", "Year oneliner was added"),
    ("%[%s]om", "Message"),
    // Lastonline Cookies
    ("%[%s]Lu", "Username"),
    ("%[%s]Lg", "Primary groupname"),
    ("%[%s]Lt", "User's tagline"),
    ("%[%s]Li", "Time of login"),
    ("%[%s]Lo", "Time of logout"),
    ("%[%s]LU", "Amount of bytes uploaded"),
    ("%[%s]LD", "Amount of bytes downloaded"),
    ("%[%s]Ls", "Actions the user did"),
    // New Directories Cookies
    ("%[%s]ND", "Newest directory, absolute path"),
    ("%[%s]Nd", "Newest directory, dirname only"),
    ("%[%s]Na", "Age"),
    ("%[%s]Nm", "Creator"),
    ("%[%s]Ns", "Files + Size"),
    // Nuke/Unnuke Cookies
    ("%[%s]KD", "Nuked/Unnuked directory, absolute path"),
    ("%[%s]Kd", "Nuked/Unnuked directory, dirname only"),
    ("%[%s]Ka", "Age"),
    ("%[%s]Kr", "Reason/Comment"),
    ("%[%s]Kn", "Nukee/Old Nukee"),
    ("%[%s]KN", "Nuker/Unnuker"),
    ("%[%s]Ks", "Multiplier + Size"),
    // Multipurpose stats Cookies
    ("%[%s]Gb", "Amount of bytes"),
    ("%[%s]GN", "Times nuked"),
    ("%[%s]Gs", "Speed in speed unit"),
    ("%[%s]Gn", "Bytes nuked"),
    ("%[%s]Gt", "User's tagline"),
    ("%[%s]Gu", "Username"),
    ("%[%s]Gg", "Primary group"),
    ("%[%s]Gf", "Number of files"),
    ("%[%s]Gp", "Percentage of total bytes"),
    ("%[%s]Gd", "Group description"),
    ("%[%s]Gm", "Number of group members"),
];